### PR TITLE
rest: workflow logs refactoring

### PR DESCRIPTION
**Pull request by dinosk**
* Modifies get_workflow_logs method to return the logs from the jobs
  of the workflow, ordered by creation date, and the engine specific
  data.

Connects https://github.com/reanahub/reana-client/issues/218

Signed-off-by: Dinos Kousidis <dinos.kousidis@cern.ch>

### CODE REVIEW

**Comment by diegodelemos** [comment]
tldr;
I have tested locally and I only get good workflow logs for CWL, Yadage is showing something rather weird and Serial is empty. Regarding jobs logs they are missing for the three engines.

Longer:
I have tested locally manually rebasing master and removing [the breakpoint in R-C PR](https://github.com/reanahub/reana-client/pull/230/files#diff-19bed1e7334d00a24f059e517c55f01dR477). I have found the following:
**Serial**
```console
~/reana-demo-helloworld $ reana-client run
[INFO] Creating a workflow...
workflow.1
[INFO] Uploading files...
File code/helloworld.py was successfully uploaded.
File data/names.txt was successfully uploaded.
[INFO] Starting workflow...
workflow.1 has been started.
~/reana-demo-helloworld $ reana-client status -w workflow.1
NAME       RUN_NUMBER   CREATED               STATUS     PROGRESS
workflow   1            2019-01-25T07:31:21   finished   1/1
~/reana-demo-helloworld $ reana-client logs -w workflow.1
WORKFLOW ENGINE LOGS

```

**CWL**
```console
~/reana-demo-helloworld $ reana-client run -f reana-cwl.yaml
[INFO] Creating a workflow...
[INFO] /Users/rodrigdi/.virtualenvs/r-client/bin/reana-client 1.0.20181118133959
[INFO] Resolved 'workflow/cwl/helloworld.cwl' to 'file:///Users/rodrigdi/code/reanahub/reana-demo-helloworld/workflow/cwl/helloworld.cwl'
workflow.2
[INFO] Uploading files...
File code/helloworld.py was successfully uploaded.
File data/names.txt was successfully uploaded.
[INFO] Starting workflow...
workflow.2 has been started.
~/reana-demo-helloworld $ reana-client status -w workflow.2
NAME       RUN_NUMBER   CREATED               STATUS     PROGRESS
workflow   2            2019-01-25T07:34:30   finished   1/1
~/reana-demo-helloworld $ reana-client logs -w workflow.2
WORKFLOW ENGINE LOGS
/usr/local/bin/run-cwl-workflow 0.4.0 with cwltool 1.0.20181118133959Resolved 'workflow.json#main' to 'file:///var/reana/users/00000000-0000-0000-0000-000000000000/workflows/dbd0a161-61b8-41d2-b64f-fd462a6ff237/workflow.json#main'[workflow ] initialized from file:///var/reana/users/00000000-0000-0000-0000-000000000000/workflows/dbd0a161-61b8-41d2-b64f-fd462a6ff2
37/workflow.json#main[workflow ] start[workflow ] {
    "inputfile": {
        "basename": "names.txt",
...
        "class": "File",
        "size": 34
    }
}Moving /var/reana/users/00000000-0000-0000-0000-000000000000/workflows/dbd0a161-61b8-41d2-b64f-fd462a6ff237/cwl/outdir/zYXnJU/results/greetings.txt to /var/reana/users/00000000-0000-0000-0000-000000000000/workflows/outputs/greetings.txtRemoving intermediate output directory /var/reana/users/00000000-0000-0000-0000-000000000000/workflows/dbd0a161-61b8-41d2-b64f-fd462a6ff237/cwl/outdir/L5bbVVRemoving intermediate output directory /var/reana/users/00000000-0000-0000-0000-000000000000/workflows/dbd0a161-61b8-41d2-b64f-fd462a6ff237/cwl/outdir/zYXnJUFinal process status is success{u'result': {'checksum': 'sha1$a1335504c573de07eb8a33f7732ce4b31d2b06b4', 'basename': 'greetings.txt', 'nameext': '.txt', 'nameroot': 'greetings', 'http://commonwl.org/cwltool#generation': 0, 'location': u'file:///var/reana/users/00000000-0000-0000-0000-000000000000/workflows/outputs/greetings.txt', 'class': 'File', 'size': 34}}
```

**Yadage**
```console
~/reana-demo-helloworld $ reana-client run -f reana-yadage.yaml
[INFO] Creating a workflow...
workflow.3
[INFO] Uploading files...
File code/helloworld.py was successfully uploaded.
File data/names.txt was successfully uploaded.
[INFO] Starting workflow...
workflow.3 has been started.
~/reana-demo-helloworld $ reana-client status -w workflow.3
NAME       RUN_NUMBER   CREATED               STATUS     PROGRESS
workflow   3            2019-01-25T07:32:21   finished   1/1
~/reana-demo-helloworld $ reana-client logs -w workflow.3
WORKFLOW ENGINE LOGS
this is a tracking log at 2019-01-25T07:32:25.839757this is a tracking log at 2019-01-25T07:32:25.975902this is a tracking log at 2019-01-25T07:32:31.105747this is a tracking log at 2019-01-25T07:32:36.125169this is a tracking log at 2019-01-25T07:32:41.151767this is a tracking log at 2019-01-25T07:32:46.176969this is a tracking log at 2019-01-25T07:32:51.200801
this is a tracking log at 2019-01-25T07:32:56.227125this is a tracking log at 2019-01-25T07:33:01.247272this is a tracking log at 2019-01-25T07:33:06.268055this is a tracking log at 2019-01-25T07:33:11.292573this is a tracking log at 2019-01-25T07:33:16.312260this is a tracking log at 2019-01-25T07:33:21.333781this is a tracking log at 2019-01-25T07:33:26.358505
this is a tracking log at 2019-01-25T07:33:31.379304this is a tracking log at 2019-01-25T07:33:36.403125this is a tracking log at 2019-01-25T07:33:41.426175this is a tracking log at 2019-01-25T07:33:46.453745
```

**Comment by dinosk** [comment]
Job logs are there for all three engines, shown if you pass the verbose flag.
Engine logs are stored based on what they publish in the workflow progress messages. Maybe it would make sense to have it reversed, job logs by default, workflow engine logs in verbose mode, as these are mostly internal and not targeted for users.

**Comment by diegodelemos** [comment]
I didn't update the long part description, I used `-v` but reply is still empty, like:

```console
~/reana-demo-helloworld $ reana-client logs -w workflow.3 -v
WORKFLOW ENGINE LOGS
this is a tracking log at 2019-01-25T07:32:25.839757this is a tracking log at 2019-01-25T07:32:25.975902this is a tracking log at 2019-01-25T07:32:31.105747this is a tracking log at 2019-01-25T07:32:36.125169this is a tracking log at 2019-01-25T07:32:41.151767this is a tracking log at 2019-01-25T07:32:46.176969this is a tracking log at 2019-01-25T07:32:51.200801this is a tracking log at 2019-01-25T07:32:56.227125this is a tracking log at 2019-01-25T07:33:01.247272this is a tracking log at 2019-01-25T07:33:06.268055this is a tracking log at 2019-01-25T07:33:11.292573this is a tracking log at 2019-01-25T07:33:16.312260this is a tracking log at 2019-01-25T07:33:21.333781this is a tracking log at 2019-01-25T07:33:26.358505this is a tracking log at 2019-01-25T07:33:31.379304this is a tracking log at 2019-01-25T07:33:36.403125this is a tracking log at 2019-01-25T07:33:41.426175this is a tracking log at 2019-01-25T07:33:46.453745


JOB LOGS
job id: 9dce86d4-c680-4df2-9f6f-992950f0d8a7

```

I thought that it would be the `tee` we are usually adding to the commands but there is no `tee` for helloworld, do you get job logs?

**Comment by dinosk** [comment]
:+1: Thanks for reviewing, fix added in https://github.com/reanahub/reana-client/pull/230 for not showing empty sections, also changed to show everything by default

**Pull request merged**
