### PR TITLE
Get default user if already exists

### PR DESCRIPTION
**Pull request by anton-khodak**

### CODE REVIEW

**Comment by diegodelemos** [comment]
could you please amend a bit the commit message? something like
`cli: detect if default user already exists` (before the `:` we try to write the component we are changing inside the package and after a short description) so if we have to search for it later we can easily find by keywords `cli`, `default user` or `already exists` thank you! 😃

**Comment by anton-khodak** [comment]
Done!

**Comment by anton-khodak** [comment]
yes, "detect" sounds clearer

**Comment by diegodelemos** [comment]
`reanahub/reana-workflow-controller:v0.0.1` updated on DockerHub, thanks @anton-khodak!

**Pull request merged**
