### PR TITLE
config: load configured image pull secrets

### PR DESCRIPTION
**Pull request by diegodelemos**
* Closes reanahub/reana-job-controller#230.

### CODE REVIEW

**Comment by danikam** [comment]
Hi @tiborsimko, @diegodelemos, thanks for this! Just to make sure I understand - would the env var `IMAGE_PULL_SECRETS` be the gitlab access token?

**Comment by diegodelemos** [comment]
Hello @danikam, in principle, you just need to add [REANA@gitlab.cern.ch](https://gitlab.cern.ch/reana) as Reporter member to the project where you host the images and then reana.cern.ch will be able to pull images from there, see:
Screenshot 2020-02-28 at 14 56 11

**Comment by danikam** [comment]
Ah, I see - thanks @diegodelemos! So the user shouldn't need to set this `IMAGE_PULL_SECRETS`  env var?

**Comment by diegodelemos** [comment]
No :) as long as you add the REANA user as a collaborator in the GitLab project there is nothing else you need to do, it is transparent (this `IMAGE_PULL_SECRETS ` is an internal environment variable, only the REANA system can access it).

**Comment by danikam** [comment]
Got it, thanks! Will start to test this out asap with the monojet repo images :)

**Pull request merged**
