### PR TITLE
rest: make details available for shared workflows

### PR DESCRIPTION
**Pull request by DaanRosendal**
| Command               | Allowed   |
|-----------------------|-----------|
| delete            | ❌        |
| diff                | ✅        |
| logs                  | ✅        |
| restart           | ❌        |
| start             | ❌        |
| status              | ✅        |
| stop              | ❌        |
| share-add         | ❌        |
| share-remove      | ❌        |
| share-status      | ❌        |
| close            | ❌        |
| open              | ❌        |
| download            | ✅        |
| du                  | ✅        |
| ls                   | ✅        |
| mv                 | ❌        |
| prune             | ❌        |
| rm              | ❌        |
| upload            | ❌        |
| retention-rules-list| ✅        |

Closes reanahub/reana-server#651, closes reanahub/reana-server#650

### CODE REVIEW

**Comment by mdonadoni** [comment]
Latest version before rebase is 96f3ac9

There are still many comments to address from previous PRs

**Comment by mdonadoni** [comment]
Ready to be reviewed, squashed and merged

**Review by tiborsimko — APPROVED** [review]
Works nicely :+1: with

```
- r-client #692
- r-client-go #153
- r-ui #375
- r-server #658
- r-workflow-controller #552
- r-commons #429
- r-db #216
```

Kept separate commits, amended commit log headlines, bumped reana-db and pytest-reana dependency versions.

**Comment by tiborsimko** [comment]
> Kept separate commits, amended commit log headlines, bumped reana-db and pytest-reana dependency versions.

Also, for the tests to work, I have noticed the following change:

```diff
$ g show 894a99ed -- tests/test_views.py | cat
commit 894a99ed75f53484aa8d03198c493919c45da6f6
Author: Daan Rosendal <daan.rosendal@cern.ch>
Date:   Fri Dec 15 12:35:02 2023 +0100

    feat(rest): make details available for shared workflows (#552)

    Closes reanahub/reana-server#651, closes reanahub/reana-server#650

diff --git a/tests/test_views.py b/tests/test_views.py
index 6426f77..c9b13e2 100644
--- a/tests/test_views.py
+++ b/tests/test_views.py
@@ -812,7 +812,7 @@ def test_get_workflow_status_unauthorized(
             content_type="application/json",
             data=json.dumps(cwl_workflow_with_name),
         )
-        assert res.status_code == 404
+        assert res.status_code == 500


 def test_get_workflow_status_unknown_workflow(app, user0, cwl_workflow_with_name):
@@ -1027,7 +1027,7 @@ def test_set_workflow_status_unauthorized(
             query_string={"user": random_user_uuid, "status": payload},
             content_type="application/json",
         )
-        assert res.status_code == 404
+        assert res.status_code == 500


 def test_set_workflow_status_unknown_workflow(
@@ -1230,7 +1230,7 @@ def test_get_workflow_logs_unauthorized(
             query_string={"user": random_user_uuid},
             content_type="application/json",
         )
-        assert res.status_code == 404
+        assert res.status_code == 500


 def test_start_input_parameters(
@@ -1785,7 +1785,7 @@ def test_get_workflow_retention_rules_invalid_user(app, sample_serial_workflow_i
             ),
             query_string={"user": uuid.uuid4()},
         )
-        assert res.status_code == 404
+        assert res.status_code == 500


 def test_share_workflow(
```

which I reverted in f3d2bcc  whilst merging so that CI would pass after bumping shared modules.

We can check this out later @mdonadoni

**Pull request merged**
