### PR TITLE
api: add delete file endpoint

### PR DESCRIPTION
**Pull request by diegodelemos**
* (Close reanahub/reana-client#210).

Blocked by https://github.com/reanahub/pytest-reana/pull/34.

### CODE REVIEW

**Comment by tiborsimko** [comment]
Need to update `setup.py` and the `pytest-reana` version:

```diff
diff --git a/setup.py b/setup.py
index 8602acc..947643e 100644
--- a/setup.py
+++ b/setup.py
@@ -29,7 +29,7 @@ tests_require = [
     'pytest-pep8>=1.0.6',
     'pytest>=3.8.0,<4.0.0',
     'swagger_spec_validator>=2.1.0',
-    'pytest-reana>=0.5.0.dev201811191',
+    'pytest-reana>=0.5.0.dev20181126',
 ]
 
 extras_require = {
```

... or just rebase against latest `master` :wink:

**Comment by tiborsimko** [comment]
Works well. 

Spotted one minor user warning order mismatch with globbing:

```console
$ reana-client list -w worldpopulation.serial                
NAME                                                                SIZE    LAST-MODIFIED      
data/World_historical_and_predicted_populations_in_percentage.csv   574     2018-11-27T10:08:06
code/worldpopulation.ipynb                                          19221   2018-11-27T10:08:04
$ reana-client remove data/foo -w worldpopulation.serial           
data/foo did not match any existing file.
$ reana-client remove '**/*o*' -w worldpopulation.serial              
File code/worldpopulation.ipynb was successfully deleted.
File data/World_historical_and_predicted_populations_in_percentage.csv was successfully deleted.
Something went wrong while deleting code.
[Errno 39] Directory not empty: '/reana/users/00000000-0000-0000-0000-000000000000/workflows/eb13046e-0e30-4318-bcae-60790903c821/code'
19795 bytes freed up.
$ reana-client list -w worldpopulation.serial           
NAME   SIZE   LAST-MODIFIED
```

**Comment by diegodelemos** [comment]
@tiborsimko ready

**Comment by tiborsimko** [comment]
:+1: 

When we shall be renaming `ls` and `rm`, we can also fix reporting about files/directories:

```console
reana-client remove '**/*'   -w worldpopulation.serial  
File code was successfully deleted.
File code/worldpopulation.ipynb was successfully deleted.
File data was successfully deleted.
19221 bytes freed up.
```

... and also enrich regular help with examples.  Currently people don't even know what SOURCES are:

```console
$ reana-client remove --help                                   
Usage: reana-client remove [OPTIONS] SOURCES

  Delete the specified file or pattern.
```

Merging...

**Pull request merged**
